CREATE DATABASE IF NOT EXISTS ZEPTO_PROJECT;
USE ZEPTO_PROJECT;

DROP TABLE IF EXISTS ZEPTO;

CREATE TABLE ZEPTO (
    Z_ID INT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY VARCHAR(150),
    NAME VARCHAR(150) NOT NULL,
    MRP DECIMAL(8,2),
    DISCOUNTPERCENT DECIMAL(5,2),
    AVAILABLEQUANTITY INT,
    DISCOUNTEDSELLINGPRICE DECIMAL(8,2),
    WEIGHTINGMS INT,
    OUTOFSTOCK VARCHAR(10),   -- Stores 'True' / 'False' directly from CSV
    QUANTITY INT
);

-- Data exploration

-- count of rows
SELECT COUNT(*) FROM ZEPTO;

-- SAMPLE DATA
SELECT * FROM ZEPTO limit 100;

-- CHECKING NULL VALUES
SELECT * FROM ZEPTO WHERE CATEGORY IS NULL 
                     OR  NAME IS NULL
                     OR MRP IS NULL
                     OR DISCOUNTPERCENT IS NULL
                     OR AVAILABLEQUANTITY IS NULL
                     OR DISCOUNTEDSELLINGPRICE IS NULL
                     OR WEIGHTINGMS IS NULL
                     OR OUTOFSTOCK IS NULL
                     OR QUANTITY IS NULL;

-- DIFFERENT PRODUCT CATEGORIES
SELECT DISTINCT CATEGORY FROM ZEPTO order by CATEGORY;

-- PRODUCTS IN STOCK VS OUT OF STOCK

SELECT OUTOFSTOCK , COUNT(Z_ID)
FROM ZEPTO 
GROUP BY OUTOFSTOCK;

-- PRODUCTS NAMES PRESENT MULTIPLE TIMES
SELECT NAME,COUNT(Z_ID) AS PRODUCTS_COUNT
FROM zeptO
group by NAME
having PRODUCTS_COUNT > 1
ORDER BY COUNT(Z_ID) DESC;


 -- DATA CLEANING
 SELECT * FROM ZEPTO WHERE MRP=0 OR DISCOUNTEDSELLINGPRICE=0;
 
 DELETE FROM ZEPTO
 WHERE mrp=0;
 
 -- convert paise to rupees
 
SET SQL_SAFE_UPDATES = 0;
UPDATE ZEPTO SET MRP=MRP/100 , DISCOUNTEDSELLINGPRICE=DISCOUNTEDSELLINGPRICE/100;
SET SQL_SAFE_UPDATES = 1;
SELECT MRP , DISCOUNTEDSELLINGPRICE FROM ZEPTO;

-- DATA ANALYSIS

-- Q1. Find the top 10 best-value products based on the discount percentage.

SELECT DISTINCT NAME,MRP,DISCOUNTPERCENT
FROM ZEPTO
ORDER BY DISCOUNTPERCENT DESC
LIMIT 10;

-- Q2.What are the Products with High MRP but Out of Stock

SELECT DISTINCT NAME,MRP,OUTOFSTOCK
FROM ZEPTO 
WHERE OUTOFSTOCK="TRUE" AND MRP>300
ORDER BY MRP DESC;

-- Q3.Calculate Estimated Revenue for each category
SELECT CATEGORY ,
SUM(DISCOUNTEDSELLINGPRICE * QUANTITY)  AS TOTAL_REVENUE
FROM ZEPTO
GROUP BY CATEGORY
ORDER BY TOTAL_REVENUE DESC;


-- Q4. Find all products where MRP is greater than ₹500 and discount is less than 10%.
SELECT DISTINCT NAME , MRP, DISCOUNTPERCENT
FROM ZEPTO
WHERE MRP>500 AND DISCOUNTPERCENT > 10
ORDER BY MRP DESC ,DISCOUNTPERCENT DESC;


-- Q5. Identify the top 5 categories offering the highest average discount percentage.
SELECT CATEGORY,ROUND(AVG(DISCOUNTPERCENT),2) AS HIGHEST_AVG
FROM ZEPTO
GROUP BY CATEGORY
ORDER BY HIGHEST_AVG DESC
LIMIT 5;


-- Q6. Find the price per gram for products above 100g and sort by best value.
SELECT distinct NAME,WEIGHTINGMS,DISCOUNTEDSELLINGPRICE,
ROUND(DISCOUNTEDSELLINGPRICE / WEIGHTINGMS,2) AS PRICE_PER_GRAM
FROM ZEPTO
WHERE WEIGHTINGMS>=100
ORDER BY PRICE_PER_GRAM;

-- Q7.Group the products into categories like Low, Medium, Bulk.
SELECT DISTINCT name, weightInGms,
CASE WHEN weightInGms < 1000 THEN 'Low'
	WHEN weightInGms < 5000 THEN 'Medium'
	ELSE 'Bulk'
END AS weight_category
FROM zepto;

-- Q8.What is the Total Inventory Weight Per Category 
SELECT CATEGORY,
SUM(WEIGHTINGMS * QUANTITY) AS TOTAL_WEIGHT
FROM ZEPTO
GROUP BY CATEGORY
ORDER BY TOTAL_WEIGHT;






























